version: '3.8'

services:
  db:
    image: postgres:16.1
    container_name: orders-ms
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=orders_ms
      - POSTGRES_USER=camilog
      - POSTGRES_PASSWORD=123456789
    ports:
      - "5432:5432"
